authors = ["Misael Cureno Sanchez <curenosm@ciencias.unam.mx>"]
desc = "This is just an example of description"
name = "Plots Examples"
keywords = ["plotting examples"]
license = "MIT"
uuid = "4cf51e78-14cf-4c74-b016-0058f85bafb7"
version = "1.0.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
PlotThemes = "ccf2f8ad-2431-5c83-bf29-c5338b663b6a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
Documenter = "1"
